version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nada-docker
    ports:
      - 8282:80
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: nada_docker
      DB_USERNAME: nada_user
      DB_PASSWORD: nada_password      
  mysql:
      image: mysql:5.7
      ports:
        - 13306:3306
      environment:
        MYSQL_DATABASE: nada_docker
        MYSQL_USER: nada_user
        MYSQL_PASSWORD: nada_password
        MYSQL_ROOT_PASSWORD: root
