version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nada5_docker
    ports:
      - 8283:80
    volumes:
      - .:/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: nada5_docker
      DB_USERNAME: nada_user
      DB_PASSWORD: nada_password      
  mysql:
      image: mysql:5.7
      container_name: mysql-57
      restart: always
      ports:
        - 13306:3306
      environment:
        MYSQL_DATABASE: nada5_docker
        MYSQL_USER: nada_user
        MYSQL_PASSWORD: nada_password
        MYSQL_ROOT_PASSWORD: root
