version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nada5_docker
    ports:
      - 8283:80
    volumes:
      - .:/app
    links:
      - sqlsrv
    environment:
      DB_HOST: sqlsrv
      DB_DATABASE: nada5
      DB_USERNAME: sa
      DB_PASSWORD: yourStrong(!)Password  
  sqlsrv:
      image: "mcr.microsoft.com/mssql/server:latest"