version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: nada5_docker
    ports:
      - 8283:80
    volumes:
      - .:/app
    environment:
      DB_HOST: localhost
      DB_DATABASE: nada
      DB_USERNAME: sa
      DB_PASSWORD: yourStrong(!)Password